# Online linter: https://rhysd.github.io/actionlint/

name: build

on: 
  push:
    branches:
      - master
    paths-ignore:
    - 'doc/**'
    - 'README.md'
    - 'README.rst'
    - 'COPYING'
  pull_request:
    branches:
      - master    
    paths-ignore:
    - 'doc/**'
    - 'README.md'
    - 'README.rst'
    - 'COPYING'
  release:
    types:
      - published

env:
  CIBW_BUILD: cp37-* cp38-* cp39-*
  # Skip 32-bit platforms
  CIBW_SKIP: "*-win32 *-manylinux_i686"
  CIBW_TEST_REQUIRES: pytest pytest-xdist
  CIBW_TEST_COMMAND: pytest -n 3 {project}/sumu/tests


jobs:
  
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.2.2

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

          
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      # Apparently no way to read these from pyproject.toml
      # https://stackoverflow.com/a/58756491
      - name: Install build dependencies
        run: pip install cython>=0.29.17 numpy

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz


  coverage_analysis:
    name: Test coverage analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      # Apparently no way to read these from pyproject.toml
      # https://stackoverflow.com/a/58756491
      - name: Install build dependencies
        run: pip install cython>=0.29.17 numpy

      - name: Install package and run tests
        env:
          CYTHON_TRACE: 1
        run: |
          python -m pip install pytest pytest-cov coverage
          # Without "--editable" pip builds a wheel which doesn't allow Cython coverage analysis
          python -m pip install --editable .
          mkdir codecov && pytest -v --cov=. --cov-report=xml:codecov/coverage.xml

      - name: Upload coverage.xml to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: codecov
          fail_ci_if_error: true


  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # Uncomment for testing
          # repository_url: https://test.pypi.org/legacy/
